var context = require('../context')
var assert = require('assert')
describe('group.js', function() {
    this.timeout(global.timeout)
    var Group = null
    var User = null
    before(function*(done) {
        yield context.init()
        var Client = require('../../lib')
        Group = new Client.Group()
        User = new Client.User()
        return done()
    })
    it('group/add', function*(done) {
        var data = yield Group.add('develop')
        var data = yield Group.add('develop' + Math.random())
        data.status.should.equal(200)
        var data = yield Group.add()
        data.status.should.equal(400)
        var data = yield Group.add('develop')
        data.status.should.equal(409)
        done()
    })
    it('group/list', function*(done) {
        var data = yield Group.list()
        data.status.should.equal(200)
        done()
    })
    it('group/users/add', function*(done) {
        var data1 = yield User.getMyAccount()
        var data = yield Group.addUser('develop', data1.uuid)
        data.status.should.equal(200)
        var data = yield Group.addUser()
        data.status.should.equal(400)
        var data = yield Group.addUser('develop123aaa', data1.uuid)
        data.error.should.equal('group_not_exist')
        var data = yield Group.addUser('develop', '1223')
        data.error.should.equal('user_not_exist')
        done()
    })
    it('group/users', function*(done) {
        var data = yield Group.getUserList('develop')
        data.status.should.equal(200)
        var data = yield Group.getUserList()
        data.status.should.equal(400)
        var data = yield Group.getUserList('develop123ewq')
        data.status.should.equal(409)
        done()
    })
    it('group/rename', function*(done) {
        var data = yield Group.rename('develop', 'develop')
        data.status.should.equal(200)
        var data = yield Group.rename()
        data.status.should.equal(400)
        var data = yield Group.rename('develop123rfv', 'develop111')
        data.error.should.equal('old_group_not_exist')
        var data = yield Group.rename('develop123rfv', 'develop')
        data.error.should.equal('new_group_existed')
        done()
    })

 it('group/users/remove', function*(done) {
        var data1 = yield User.getMyAccount()
        var data = yield Group.removeUser('develop', data1.uuid)
        data.status.should.equal(200)
        var data = yield Group.removeUser()
        data.status.should.equal(400)
        var data = yield Group.removeUser('develop123aaa', data1.uuid)
        data.error.should.equal('group_not_exist')
        var data = yield Group.removeUser('develop123aaa', '1223')
        data.error.should.equal('user_not_exist')
        done()
    })
   it('group/remove', function*(done) {
        var data = yield Group.remove('develop')
        data.status.should.equal(200)
        var data = yield Group.remove()
        data.status.should.equal(400)
        var data = yield Group.remove('develop123ewq')
        data.status.should.equal(409)
        done()
    })

})
