var context = require('../context')
var assert = require('assert')
describe('group.js', function() {
    this.timeout(global.timeout)
    var Group = null
    var Member = null
    before(function*(done) {
        yield context.init()
        var Client = require('../../lib')
        Group = new Client.Group()
        Member = new Client.Member()
        return done()
    })
    it('group/add', function*(done) {
        var data = yield Group.add('develop')
        var data = yield Group.add('develop' + Math.random())
        data.status.should.equal(200)
        var data = yield Group.add()
        data.status.should.equal(400)
        var data = yield Group.add('develop')
        data.status.should.equal(409)
        done()
    })
    it('group/list', function*(done) {
        var data = yield Group.list()
        data.status.should.equal(200)
        done()
    })
    it('group/members/add', function*(done) {
        var data1 = yield Member.getMyAccount()
        var data = yield Group.addMember('develop', data1.uuid)
        data.status.should.equal(200)
        var data = yield Group.addMember()
        data.status.should.equal(400)
        var data = yield Group.addMember('develop123aaa', data1.uuid)
        data.error.should.equal('group_not_exist')
        var data = yield Group.addMember('develop', '1223')
        data.error.should.equal('member_not_exist')
        done()
    })
    it('group/members', function*(done) {
        var data = yield Group.getMemberList('develop')
        data.status.should.equal(200)
        var data = yield Group.getMemberList()
        data.status.should.equal(400)
        var data = yield Group.getMemberList('develop123ewq')
        data.status.should.equal(409)
        done()
    })
    it('group/rename', function*(done) {
        var data = yield Group.rename('develop', 'develop')
        data.status.should.equal(200)
        var data = yield Group.rename()
        data.status.should.equal(400)
        var data = yield Group.rename('develop123rfv', 'develop111')
        data.error.should.equal('old_group_not_exist')
        var data = yield Group.rename('develop123rfv', 'develop')
        data.error.should.equal('new_group_existed')
        done()
    })

 it('group/members/remove', function*(done) {
        var data1 = yield Member.getMyAccount()
        var data = yield Group.removeMember('develop', data1.uuid)
        data.status.should.equal(200)
        var data = yield Group.removeMember()
        data.status.should.equal(400)
        var data = yield Group.removeMember('develop123aaa', data1.uuid)
        data.error.should.equal('group_not_exist')
        var data = yield Group.removeMember('develop123aaa', '1223')
        data.error.should.equal('member_not_exist')
        done()
    })
   it('group/remove', function*(done) {
        var data = yield Group.remove('develop')
        data.status.should.equal(200)
        var data = yield Group.remove()
        data.status.should.equal(400)
        var data = yield Group.remove('develop123ewq')
        data.status.should.equal(409)
        done()
    })

})
